### ISSUE TITLE
RPG部分について何から手を付けていいかわからない

### ISSUE THREAD

**Issue by Shotaro64** [konan-pbl-2018/teamC#1]
RPG部分について話し合いをし仕様がある程度決まったのですがシューティングからの移行、文字の表示等わからないことが多いです。

**Comment by n-nitta** [comment]
（説明したこと）
・メインクラスでゲーム状態を追加する方法。
・RPGContainerの画面の作り方。

（まだ説明していないこと）
・RPG画面に切り替える具体的な方法。
・PRG画面上での操作方法、画面の書き換え方法。
